# Deploy SQL Server 2022 VM to Azure
# Usage: pwsh ./00-deploy-azure.ps1
$ErrorActionPreference = 'Stop'

$ResourceGroup = 'rg-sqlmirror-demo'
$Location      = 'japaneast'
$DeploymentName = "sqlmirror-$(Get-Date -Format 'yyyyMMddHHmm')"
$BicepFile     = Join-Path $PSScriptRoot '..\infra\main.bicep'

# パスワード
$AdminPassword = 'Adm!nP@ss_2026_demo'
$SqlPassword   = 'F@bric_Strong_Pwd_2026'

# SendGrid (空文字ならメール通知なしで Functions デプロイ)
$SendGridApiKey = $env:SENDGRID_API_KEY ?? ''
$AlertEmailTo   = $env:ALERT_EMAIL_TO ?? ''
$AlertEmailFrom = $env:ALERT_EMAIL_FROM ?? 'noreply@sqlmirror-demo.example.com'

# クライアント IP を取得して NSG を絞る (デモ簡略化)
try {
    $myIp = (Invoke-RestMethod -Uri 'https://api.ipify.org' -TimeoutSec 5).Trim()
    $allowedCidr = "$myIp/32"
    Write-Host "==> 検出したクライアント IP: $myIp" -ForegroundColor Cyan
} catch {
    Write-Host "==> クライアント IP 検出失敗。'*' を使用 (デモ用)" -ForegroundColor Yellow
    $allowedCidr = '*'
}

Write-Host "==> Resource Group: $ResourceGroup ($Location)" -ForegroundColor Cyan
az group create --name $ResourceGroup --location $Location --tags Environment=Demo Project=SQLMirror -o none

Write-Host "==> Bicep デプロイ開始 (~10-15 分)" -ForegroundColor Cyan
$result = az deployment group create `
    --resource-group $ResourceGroup `
    --name $DeploymentName `
    --template-file $BicepFile `
    --parameters `
        adminPassword=$AdminPassword `
        sqlAuthPassword=$SqlPassword `
        allowedSourceCidr=$allowedCidr `
        sendGridApiKey=$SendGridApiKey `
        alertEmailTo=$AlertEmailTo `
        alertEmailFrom=$AlertEmailFrom `
    --query 'properties.outputs' `
    -o json | ConvertFrom-Json

if ($LASTEXITCODE -ne 0) { throw "Deployment failed" }

Write-Host ""
Write-Host "✅ デプロイ完了" -ForegroundColor Green
Write-Host ""
Write-Host "接続情報:" -ForegroundColor Cyan
Write-Host "  SQL Endpoint  : $($result.sqlServerEndpoint.value)"
Write-Host "  Public IP     : $($result.vmPublicIp.value)"
Write-Host "  FQDN          : $($result.vmFqdn.value)"
Write-Host "  SQL Login     : $($result.sqlAuthLoginName.value)"
Write-Host "  SQL Password  : $SqlPassword"
Write-Host "  RDP User      : azureuser"
Write-Host "  RDP Password  : $AdminPassword"
Write-Host "  Functions App : $($result.funcAppName.value)"
Write-Host "  Functions URL : $($result.funcAppUrl.value)"
Write-Host "  App Insights  : $($result.appInsightsName.value)"
Write-Host ""

# 環境変数として保存（後続スクリプト用）
$envFile = Join-Path $PSScriptRoot '.azure-env.ps1'
@"
# Auto-generated by 00-deploy-azure.ps1
`$env:SQL_SERVER  = '$($result.sqlServerEndpoint.value)'
`$env:SQL_FQDN    = '$($result.vmFqdn.value)'
`$env:SQL_PUBLIC_IP = '$($result.vmPublicIp.value)'
`$env:SQL_LOGIN   = '$($result.sqlAuthLoginName.value)'
`$env:SQL_PASSWORD = '$SqlPassword'
`$env:FUNC_APP_NAME = '$($result.funcAppName.value)'
`$env:FUNC_APP_URL  = '$($result.funcAppUrl.value)'
"@ | Set-Content -Path $envFile -Encoding utf8

Write-Host "環境変数は $envFile に保存。次は: . ./.azure-env.ps1; ./02-restore-adventureworkslt-azure.ps1" -ForegroundColor Yellow
